### ISSUE TITLE
Failed to start vncserver@.service

### ISSUE THREAD

**Issue by nicholasadamou** [Re4son/RPi-Tweaks#3]
I downloaded and enabled the `vncserver@` service, however, `systemctl` doesn't want to start it.

After running: `sudo systemctl start /ib/systemd/system/vncserver@.service` I am presented with the following error:

`Failed to start ib-systemd-system-vncserver\x40.service.mount: Unit ib-systemd-system-vncserver\x40.service.mount not found.`

Why?

Additionally, simply running: `sudo systemctl start vncserver@.service` will invoke the following error:

```
Failed to start vncserver@.service: Unit name vncserver@.service is missing the instance name.

See system logs and 'systemctl status vncserver@.service' for details.
```

Running: `systemctl status vncserver@.service` outputs: 

`Failed to get properties: Unit name vncserver@.service is neither a valid invocation ID nor unit name.`

**Comment by Re4son** [comment]
Just assign a unique ID to the instant you are starting, e.g.
sudo systemctl enable vncserver@1.service && sudo systemctl start vncserver@1.service

Notice the "1" after the @? That's the ID it is expecting.

Please let me know how you go

**Comment by nicholasadamou** [comment]
`sudo systemctl enable vncserver@1.service` returns: 

```
failed to enable unit: unit file vncserver@1.service does not exist`
``` 

This does work when I type the following command: `sudo systemctl enable /lib/systemd/system/vncserver@.service`.

However, I am able to start the service after typing: 

`sudo systemctl enable /lib/systemd/system/vncserver@.service && sudo systemctl start vncserver@1.service`

**Comment by Re4son** [comment]
Should work. This just worked for me without any problems:


root@kali-pi:/home/re4son# wget -O /lib/systemd/system/vncserver@.service https://github.com/Re4son/vncservice/raw/master/vncserver@.service

root@kali-pi:/home/re4son# systemctl enable vncserver@1.service && sudo systemctl start vncserver@1.service

root@kali-pi:/home/re4son#  systemctl status vncserver@1
â vncserver@1.service - VNC Service for remote desktop sharing
   Loaded: loaded (/lib/systemd/system/vncserver@.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-04-10 06:28:49 AEST; 26s ago
  Process: 840 ExecStart=/usr/bin/vncserver :1 (code=exited, status=0/SUCCESS)

Are you using Sticky Fingers or stock Kali?

**Comment by nicholasadamou** [comment]
Okay, well after re-running the below commands, everything seems to be running smoothly now. Don't know what was going wrong, but seems to work now. 

1. `wget -O /lib/systemd/system/vncserver@.service https://github.com/Re4son/vncservice/raw/master/vncserver@.service`

2. `systemctl enable vncserver@1.service && sudo systemctl start vncserver@1.service`

**Comment by neofit77** [comment]
Tnx @nicholasadamou this is solved my problem

**Comment by mabmgc** [comment]
Thank you, @nicholasadamou seem to work with other services as well!
- Macchanger
   changemac@.service  => changemac@eth0.service
